name: Deploy app

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test frontend
        run: npm run test:frontend
      - name: Test backend
        run: npm run test:backend
      #- name: Install Playwright Browsers
      #  run: npx playwright install --with-deps
      #- name: Test e2e
      #  run: npx playwright test
      - name: Deploy
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}