name: Periodic health check

on:
  schedule:
    - cron: '0 8 * * 1' # every monday at 8

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check health of deployed app
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://fullstackopen-part11-20.fly.dev/health